apiVersion: v1
kind: Secret
metadata:
  name: flowise-secret
  namespace: flowise
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
  flowise-password: {{ .Values.flowise.password | b64enc }}
  flowise-security-key: {{ .Values.flowise.security_key | b64enc }}