name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (ex: 1.0.0)'
        type: string
        required: true

env:
  DOCKER_BUILD_IMAGE_NAME: flowise_flowise
  IMAGE_NAME: flowise
  VERSION: latest

jobs:
  build:
    name: 🎉 Release Build ${{ inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 🔨 Build docker image
        run: docker build . -f Dockerfile -t $DOCKER_BUILD_IMAGE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷 Tag and Push
        id: prep
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Tag the latest image with the correct version
          NEW_IMAGE_TAG=$IMAGE_ID:${{ inputs.version }}
          docker tag $DOCKER_BUILD_IMAGE_NAME $NEW_IMAGE_TAG
          # Push the image to github registry
          docker push $NEW_IMAGE_TAG